name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: PHP Syntax Checker
      uses: StephaneBour/actions-php-lint@7.3
    
    - name: Install composer
      uses: php-actions/composer@v1
      
    - name: Run PHPUnit
      uses: php-actions/phpunit@v1
      with:
        config: ./phpunit.xml
        memory: 256M
